# Generated by Django 5.0.6 on 2024-07-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=254, verbose_name='author')),
                ('title', models.CharField(max_length=254, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='update date')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='publish date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
        ),
    ]
