# Generated by Django 5.0.6 on 2024-07-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publish date'),
        ),
    ]
