# Generated by Django 5.0.6 on 2024-07-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_article_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='journalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
    ]
