# Generated by Django 5.0.6 on 2024-07-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='bio',
            field=models.TextField(default='', verbose_name='Bio'),
        ),
    ]
